### ISSUE TITLE
Important Things to Support

### ISSUE THREAD

**Issue by ThatJoeMoore** [byu-oit/kotlin-uapi#2]
- [ ] Customize simple ID names
- [ ] Root resources (for single-resource APIs)
- [ ] [Contexts](https://github.com/byu-oit/UAPI-Specification/blob/master/University%20API%20Specification.md#52-contexts)
- [ ] Ability to send back 404 when not authorized to view resource instead of default 403 (useful, for example, with restricted person records)

(More coming)

**Comment by yoshutch** [comment]
- [ ] [contexts](https://github.com/byu-oit/UAPI-Specification/blob/master/University%20API%20Specification.md#52-contexts)?

**Comment by ThatJoeMoore** [comment]
Ooh, yeah. Definitely.
